apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-operator
spec:
  chartRef:
    kind: HelmChart
    name: flux-operator
    namespace: flux-operator
  interval: 10m
  chart:
    spec:
      chart: flux-operator
      sourceRef:
        kind: HelmRepository
        name: flux-operator
        namespace: flux-operator
      version: ">=0.14.0"
  values: {}
