apiVersion: flux-operator.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  sync:
    url: https://github.com/aplacaba/kind-flux-local.git
    branch: main
    path: clusters/prod
    interval: 1m
---
