kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        listenAddress: "127.0.0.1"
      - containerPort: 30443
        hostPort: 30443
        listenAddress: "127.0.0.1"
      - containerPort: 3000
        hostPort: 30090
        listenAddress: "127.0.0.1"
      - containerPort: 22
        hostPort: 30022
        listenAddress: "127.0.0.1"
  - role: worker
---
