apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  url: oci://ghcr.io/traefik/helm/traefik
  ref:
    semver: ">=32.0.0"
